import React, { useState, useEffect } from 'react'

/* Screen 3 — SME Onboarding Brief (Full Sprint Support)
   AI-generated context package · document layout with left nav + right rail */

const Ico3 = {
  link: (p) => (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke="currentColor" strokeWidth="1.3" strokeLinecap="round" {...p}>
      <path d="M5.5 3 L8 0.5 A1.5 1.5 0 0 1 10.5 3 L8 5.5"/>
      <path d="M5.5 8 L3 10.5 A1.5 1.5 0 0 1 0.5 8 L3 5.5"/>
      <path d="M4 7 L7 4"/>
    </svg>
  ),
  chev: (p) => (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" {...p}>
      <path d="M4 2.5 L7.5 5.5 L4 8.5"/>
    </svg>
  ),
  check3: (p) => (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" {...p}>
      <path d="M2.5 5.8 L4.6 7.8 L8.6 3.4"/>
    </svg>
  ),
  spark3: (p) => (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="currentColor" {...p}>
      <path d="M5.5 0.5 L6.3 4.2 L10 5 L6.3 5.8 L5.5 9.5 L4.7 5.8 L1 5 L4.7 4.2 Z"/>
    </svg>
  ),
};

// ─── Brief Nav ──────────────────────────────────────────────────────
function BriefNav({ active = "sprint-goals", onJump }) {
  const sections = [
    { id: "client",       n: "01", t: "Client Overview" },
    { id: "team",         n: "02", t: "Your Team" },
    { id: "sprint-goals", n: "03", t: "Sprint Goals" },
    { id: "domain",       n: "04", t: "Domain Context" },
    { id: "norms",        n: "05", t: "Working Norms" },
    { id: "quickstart",   n: "06", t: "Quick Start" },
  ];
  return (
    <nav className="brief-nav">
      <div className="brand"><span className="dot"/>Toptal</div>
      <div className="brand-sub">SME · Onboarding</div>

      <div className="nav-heading">On this page</div>
      <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>
        {sections.map((s) => (
          <a key={s.id}
             className={"nav-item" + (s.id === active ? " active" : "")}
             onClick={() => onJump && onJump(s.id)}>
            <span className="nav-num">{s.n}</span>
            <span>{s.t}</span>
          </a>
        ))}
      </div>

      <div className="brief-progress">
        <div className="lbl"><span>Reading</span><span>32%</span></div>
        <div className="bar"><div className="fill"/></div>
      </div>
    </nav>
  );
}

// ─── Brief Main Content ─────────────────────────────────────────────
function BriefMain({ checks, setChecks }) {
  const toggle = (i) => setChecks((cs) => cs.map((v, ix) => ix === i ? !v : v));
  const items = [
    { t: "Accept invite to Halyard GitHub org",   sub: "Repo: halyard/api-migration · main + sprint-14 branches", act: "OPEN INVITE" },
    { t: "Join Slack channel #eng-halyard",        sub: "Sprint standups posted here · pinned doc: sprint-14 plan", act: "JOIN" },
    { t: "30-min sync with Maya (lead)",           sub: "Today 16:00 CET · Hangouts link in your calendar",        act: "RSVP" },
    { t: "Skim Domain Context section above",     sub: "Architecture notes, key decisions, surface area you'll touch", act: "OPEN" },
    { t: "Pick up HC-248 (Ingress fails on burst)", sub: "Marked blocked since May 20 · Maya already triaged",     act: "ASSIGN" },
  ];

  return (
    <article className="brief-main" id="brief-main">
      <div className="brief-meta-top">
        <span className="ai-stamp"><span className="pulse"/> Generated by Toptal AI · 09:43 UTC</span>
        <span>For Priya Nair · 12-min read</span>
      </div>

      <div className="brief-hello">Onboarding brief · Sprint Support</div>
      <h1 className="brief-title">Halyard Capital · API Migration</h1>
      <p className="brief-deck">
        Pre-Series-B fintech moving their core trading API from a legacy Python monolith to a Go services mesh on K8s. You're joining <b>Sprint 14</b> (day 6 of 10) to unblock Kubernetes ingress work. Everything below is generated from the engagement's data platform — no need to ask the team for context.
      </p>

      {/* 01 — Client Overview */}
      <section className="brief-section" id="client">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">01</span>
          <h2 className="brief-section-h">Client Overview</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="brief-prose">
          <p>
            <b>Halyard Capital</b> is a NYC-based quantitative trading firm (Series A · 42 FTE) building proprietary execution infrastructure for FX and futures. Toptal has worked with them for 14 months across two engagements — first on data ingestion (closed Feb), now on the API migration.
          </p>
          <p>
            The migration moves Halyard off a monolithic Python API onto a Go service mesh. Why it matters: the legacy stack caps them at ~120 req/s during market open; the new stack needs to hit 4,000 req/s before September.
          </p>
        </div>
        <div className="client-cells">
          <div className="client-cell"><div className="k">Industry</div><div className="v">Quantitative trading</div></div>
          <div className="client-cell"><div className="k">Engagement length</div><div className="v mono">14mo · ext.</div></div>
          <div className="client-cell"><div className="k">Stack</div><div className="v">Go · K8s · Postgres</div></div>
        </div>
      </section>

      {/* 02 — Your Team */}
      <section className="brief-section" id="team">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">02</span>
          <h2 className="brief-section-h">Your Team</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="brief-prose" style={{ marginBottom: 6 }}>
          5 people in the engagement plus you. Marcus flagged the skill gap that triggered this request. CET working hours; daily standup at 10:00 CET.
        </div>
        <div className="team">
          <div className="tm">
            <div className="av c1">MR</div>
            <div className="info">
              <div className="name">Maya Rivera</div>
              <div className="role">Lead engineer · Halyard Capital</div>
              <div className="handle">@maya · Berlin · CET</div>
            </div>
          </div>
          <div className="tm">
            <div className="av you">PN</div>
            <div className="info">
              <div className="name">Priya Nair <span className="you-chip">You</span></div>
              <div className="role">SME · Platform Infrastructure · Toptal</div>
              <div className="handle">@pnair · Amsterdam · CET</div>
            </div>
          </div>
          <div className="tm">
            <div className="av c2">JK</div>
            <div className="info">
              <div className="name">Jonas Kreft</div>
              <div className="role">Backend · Go services</div>
              <div className="handle">@jonas · Vienna · CET</div>
            </div>
          </div>
          <div className="tm">
            <div className="av c3">SN</div>
            <div className="info">
              <div className="name">Sana Noor</div>
              <div className="role">Frontend · Next.js</div>
              <div className="handle">@sana · Lahore · PKT</div>
            </div>
          </div>
          <div className="tm">
            <div className="av c4">DT</div>
            <div className="info">
              <div className="name">Diego Toledo</div>
              <div className="role">Platform · SRE</div>
              <div className="handle">@dtoledo · São Paulo · BRT</div>
            </div>
          </div>
          <div className="tm">
            <div className="av c5">EL</div>
            <div className="info">
              <div className="name">Elena Larsen</div>
              <div className="role">Delivery lead · Toptal</div>
              <div className="handle">@elena · Copenhagen · CET</div>
            </div>
          </div>
        </div>
      </section>

      {/* 03 — Sprint Goals */}
      <section className="brief-section" id="sprint-goals">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">03</span>
          <h2 className="brief-section-h">Sprint Goals · Sprint 14 (Day 6 of 10)</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="goals">
          <div className="goal">
            <div className="goal-status done" title="Done"/>
            <div>
              <div className="goal-title">Migrate the user-auth surface to the Go service</div>
              <div className="goal-sub">Closed yesterday by Jonas · 2-week throughput target met</div>
            </div>
            <div className="goal-tag done">Done</div>
          </div>
          <div className="goal">
            <div className="goal-status blocked" title="Blocked"/>
            <div>
              <div className="goal-title">Get ingress stable under burst load</div>
              <div className="goal-sub">HC-248 · HC-252 · 30% drop at peak — this is what you're here for. Maya has triage notes pinned in #eng-halyard.</div>
            </div>
            <div className="goal-tag blocked">Blocked · 6d</div>
          </div>
          <div className="goal">
            <div className="goal-status active" title="In progress"/>
            <div>
              <div className="goal-title">Cut over order-pipeline reads to the new service</div>
              <div className="goal-sub">Behind a feature flag · gradual rollout planned for next sprint</div>
            </div>
            <div className="goal-tag active">In progress</div>
          </div>
          <div className="goal">
            <div className="goal-status" title="Upcoming"/>
            <div>
              <div className="goal-title">Decommission legacy Python <code style={{fontFamily:"var(--font-mono)",background:"var(--line-soft)",padding:"0 4px",borderRadius:3,fontSize:12}}>/v1/orders</code> endpoint</div>
              <div className="goal-sub">Scheduled for sprint 15 — depends on the rollout above</div>
            </div>
            <div className="goal-tag">Upcoming</div>
          </div>
        </div>
      </section>

      {/* 04 — Domain Context */}
      <section className="brief-section" id="domain">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">04</span>
          <h2 className="brief-section-h">Domain Context</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="brief-prose">
          <p>
            Ingress is <span className="pill">NGINX</span> on EKS, behind an AWS NLB. Order-pipeline traffic shares the same ingress class as auth/admin traffic; under market-open burst (~1,800 req/s) we see TCP backlog grow and 502s climb to 30% within 90 seconds. The patch in <b>v4.18.2</b> changed <code style={{fontFamily:"var(--font-mono)",background:"var(--line-soft)",padding:"0 4px",borderRadius:3,fontSize:13}}>worker_connections</code> from 4096 → 1024 — this is the most likely culprit but Maya hasn't confirmed.
          </p>
          <p>
            Decision in flight: keep NGINX or move to <span className="pill">Envoy</span>. The team is open to either. Your read here matters and will route the rest of the migration.
          </p>
        </div>
      </section>

      {/* 05 — Working Norms */}
      <section className="brief-section" id="norms">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">05</span>
          <h2 className="brief-section-h">Working Norms</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="norms">
          <div className="norm"><div className="k">Standup</div><div className="v mono">Daily · 10:00 CET<small>30 min · Hangouts · async OK if asleep</small></div></div>
          <div className="norm"><div className="k">Decision rhythm</div><div className="v">Lightweight RFC <small>Notion doc → Slack thread → ship in next sprint</small></div></div>
          <div className="norm"><div className="k">Comms primary</div><div className="v">Slack · #eng-halyard<small>DMs OK · @here for blockers only</small></div></div>
          <div className="norm"><div className="k">Code review</div><div className="v">≥ 1 approver · within 4h<small>Maya reviews infra · Jonas reviews services</small></div></div>
          <div className="norm"><div className="k">PTO / coverage</div><div className="v">Jonas out Fri PM<small>Diego covers SRE on-call</small></div></div>
          <div className="norm"><div className="k">Cultural note</div><div className="v">Direct, written-first<small>Long Slack threads &gt; meetings · skim the pinned docs</small></div></div>
        </div>
      </section>

      {/* 06 — Quick Start */}
      <section className="brief-section" id="quickstart">
        <div className="brief-section-eyebrow">
          <span className="brief-section-num">06</span>
          <h2 className="brief-section-h">Quick Start · Day 1</h2>
        </div>
        <div className="brief-section-rule"/>
        <div className="brief-prose" style={{ marginBottom: 4 }}>
          Six items, ~45 minutes total. Tick them off as you go — your delivery lead sees this state too.
        </div>
        <div className="checklist">
          {items.map((it, i) => (
            <div key={i} className={"check" + (checks[i] ? " done" : "")} onClick={() => toggle(i)}>
              <div className="check-box">{checks[i] ? <Ico3.check3/> : null}</div>
              <div>
                <div className="check-title">{it.t}</div>
                <div className="check-sub">{it.sub}</div>
              </div>
              <div className="check-action">{it.act}</div>
            </div>
          ))}
        </div>
      </section>
    </article>
  );
}

// ─── Right Meta Rail ────────────────────────────────────────────────
function BriefRail({ checks }) {
  const completed = checks.filter(Boolean).length;
  return (
    <aside className="brief-rail">
      <div className="rail-fresh">
        <div className="h"><Ico3.spark3 style={{ marginRight: 4, verticalAlign: -1 }}/> AI-generated</div>
        <div className="v">Context valid for 72 hours</div>
        <div className="sub">REFRESHES · 28 May 09:43 UTC</div>
      </div>

      <div className="rail-block">
        <div className="h">Engagement</div>
        <div className="rail-fact"><span className="k">Client</span><span className="v sans">Halyard Capital</span></div>
        <div className="rail-fact"><span className="k">Mode</span><span className="v sans">Sprint Support</span></div>
        <div className="rail-fact"><span className="k">Duration</span><span className="v">~1 sprint · 4d</span></div>
        <div className="rail-fact"><span className="k">Stage</span><span className="v sans">Onboarding</span></div>
        <div className="rail-fact"><span className="k">SLA</span><span className="v">72h · on track</span></div>
      </div>

      <div className="rail-block">
        <div className="h">Day 1 progress</div>
        <div className="rail-fact"><span className="k">Checklist</span><span className="v">{completed}/5 done</span></div>
        <div className="rail-fact"><span className="k">First sync</span><span className="v">Today 16:00 CET</span></div>
      </div>

      <div className="rail-block">
        <div className="h">Jump to</div>
        <a className="rail-link"><span>Repo · halyard/api-migration</span><span className="ico"><Ico3.link/></span></a>
        <a className="rail-link"><span>Slack · #eng-halyard</span><span className="ico"><Ico3.link/></span></a>
        <a className="rail-link"><span>Sprint board · HC-14</span><span className="ico"><Ico3.link/></span></a>
        <a className="rail-link"><span>Last incident log</span><span className="ico"><Ico3.link/></span></a>
        <a className="rail-link"><span>RFC · NGINX or Envoy</span><span className="ico"><Ico3.link/></span></a>
      </div>

      <div className="rail-block">
        <div className="h">Your delivery lead</div>
        <div style={{ display: "flex", gap: 10, alignItems: "center", padding: "8px 0" }}>
          <div className="tm" style={{ border: "none", padding: 0, background: "transparent" }}>
            <div className="av c4" style={{ width: 30, height: 30, fontSize: 11 }}>EL</div>
            <div className="info">
              <div className="name" style={{ fontSize: 12.5 }}>Elena Larsen</div>
              <div className="handle">@elena · Toptal</div>
            </div>
          </div>
        </div>
      </div>
    </aside>
  );
}

// ─── Full brief composition ─────────────────────────────────────────
function OnboardingBrief({ initialChecks }) {
  const [checks, setChecks] = useState(initialChecks || [true, true, false, false, false]);
  return (
    <div className="cad brief">
      <BriefNav active="sprint-goals"/>
      <BriefMain checks={checks} setChecks={setChecks}/>
      <BriefRail checks={checks}/>
    </div>
  );
}

function FrameBrief() {
  return <OnboardingBrief/>;
}

// Variant: scrolled-to-checklist to make Day-1 the hero in a second artboard
function FrameBriefChecklist() {
  const [checks, setChecks] = useState([true, true, true, false, false]);
  React.useEffect(() => {
    const el = document.querySelector("#brief-main-checklist #quickstart");
    if (el) el.scrollIntoView({ behavior: "instant", block: "start" });
  }, []);
  return (
    <div className="cad brief">
      <BriefNav active="quickstart"/>
      <div className="brief-main" id="brief-main-checklist" style={{ padding: "28px 56px 80px" }}>
        <div className="brief-meta-top">
          <span className="ai-stamp"><span className="pulse"/> Generated by Toptal AI · 09:43 UTC</span>
          <span>For Priya Nair · Day 1</span>
        </div>

        <div className="brief-hello">Quick start</div>
        <h1 className="brief-title" style={{ fontSize: 28, maxWidth: "26ch" }}>Six things to do today, in 45 minutes.</h1>
        <p className="brief-deck">
          Everything you need is on this page. Tick items as you go; your delivery lead sees this state too, so they know you're loading in.
        </p>

        <section className="brief-section" style={{ marginTop: 12 }}>
          <div className="brief-section-eyebrow">
            <span className="brief-section-num">06</span>
            <h2 className="brief-section-h">Quick Start · Day 1</h2>
          </div>
          <div className="brief-section-rule"/>
          <div className="checklist">
            {[
              { t: "Accept invite to Halyard GitHub org", sub: "Repo: halyard/api-migration · main + sprint-14 branches", act: "OPEN INVITE" },
              { t: "Join Slack channel #eng-halyard", sub: "Sprint standups posted here · pinned doc: sprint-14 plan", act: "JOIN" },
              { t: "30-min sync with Maya (lead)", sub: "Today 16:00 CET · Hangouts link in your calendar", act: "RSVP" },
              { t: "Skim Domain Context section above", sub: "Architecture notes, key decisions, surface area you'll touch", act: "OPEN" },
              { t: "Pick up HC-248 (Ingress fails on burst)", sub: "Marked blocked since May 20 · Maya already triaged", act: "ASSIGN" },
            ].map((it, i) => (
              <div key={i} className={"check" + (checks[i] ? " done" : "")} onClick={() => setChecks((cs) => cs.map((v, ix) => ix === i ? !v : v))}>
                <div className="check-box">{checks[i] ? <Ico3.check3/> : null}</div>
                <div>
                  <div className="check-title">{it.t}</div>
                  <div className="check-sub">{it.sub}</div>
                </div>
                <div className="check-action">{it.act}</div>
              </div>
            ))}
          </div>
        </section>

        <section className="brief-section">
          <div className="brief-section-eyebrow">
            <span className="brief-section-num">05</span>
            <h2 className="brief-section-h">Working Norms · the essentials</h2>
          </div>
          <div className="brief-section-rule"/>
          <div className="norms">
            <div className="norm"><div className="k">Standup</div><div className="v mono">Daily · 10:00 CET<small>30 min · Hangouts</small></div></div>
            <div className="norm"><div className="k">Comms</div><div className="v">Slack · #eng-halyard<small>Long threads &gt; meetings</small></div></div>
            <div className="norm"><div className="k">Code review</div><div className="v">≥ 1 approver · within 4h<small>Maya: infra · Jonas: services</small></div></div>
            <div className="norm"><div className="k">Cultural note</div><div className="v">Direct, written-first<small>Skim pinned docs before DMs</small></div></div>
          </div>
        </section>
      </div>
      <BriefRail checks={checks}/>
    </div>
  );
}

export { FrameBrief, FrameBriefChecklist, OnboardingBrief };
