import React from 'react'

/* Screen 4 — Emergency Context Card
   Condensed outage brief · 8h SLA · scannable in <2 min */

const Ico4 = {
  doc: (p) => (
    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" strokeLinecap="round" {...p}>
      <path d="M3 1.5 H8 L10.5 4 V11.5 H3 Z"/>
      <path d="M8 1.5 V4 H10.5"/>
      <path d="M5 7 H8.5 M5 9 H8.5"/>
    </svg>
  ),
  log: (p) => (
    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" {...p}>
      <rect x="2" y="2.5" width="9" height="8" rx="1.2"/>
      <path d="M4 5.5 H9 M4 7.5 H9 M4 9.5 H7"/>
    </svg>
  ),
  graph: (p) => (
    <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" {...p}>
      <path d="M1.5 11 H11.5 M2.5 11 V8 M5 11 V4 M7.5 11 V6 M10 11 V2.5"/>
    </svg>
  ),
  arrow4: (p) => (
    <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" {...p}>
      <path d="M3 7 H11 M7.5 3.5 L11 7 L7.5 10.5"/>
    </svg>
  ),
  ext: (p) => (
    <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round" {...p}>
      <path d="M5 2 H9 V6 M9 2 L4.5 6.5 M2.5 4 V9 H7.5"/>
    </svg>
  ),
};

// ─── Emergency Context Card ─────────────────────────────────────────
function EmergencyContextCard({ mobile = false, onOpenWarRoom }) {
  const card = (
    <div className="ectx">
      {/* Severity bar */}
      <div className="ectx-top">
        <div className="ectx-top-l">
          <span className="sev">P1 · Production outage</span>
          <span className="meta">Brief · ODT-P1-0042</span>
        </div>
        <div className="ectx-top-r">
          <div className="ectx-fresh">
            <span className="pulse"/> Context valid · 3h 47m
          </div>
        </div>
      </div>

      {/* Headline */}
      <div className="ectx-headline">
        <div className="ectx-eyebrow">Generated by Toptal AI · 14:10 UTC · for Priya Nair</div>
        <h1 className="ectx-title">API Gateway returning <span style={{ color: "var(--alert)" }}>503s</span> on all /v2/trade routes — 94% error rate.</h1>
        <div className="ectx-for">
          <b>Halyard Capital</b> · trading platform · degraded since <span style={{ fontFamily: "var(--font-mono)", fontSize: 12 }}>14:07 UTC</span> · 1,400 req/min failing
        </div>
      </div>

      {/* Start-here directive */}
      <div className="ectx-start">
        <div className="lbl">Start here</div>
        <div className="v">
          Join <b>#incident-halyard</b> (war room), then review the Kong rate-limit plugin config in commit <span className="code">b7e4c12</span>. Aaron Sokol on SRE has the live theory: <b>rate_limiting config</b> misconfigured in <span className="code">v2.9.1</span>, blocking all /v2/trade traffic.
        </div>
      </div>

      {/* Four sections */}
      <div className="ectx-sections">
        <div className="ectx-block">
          <div className="h">What is broken</div>
          <div className="body">
            API Gateway returning <b>503s</b> on all <span className="mono">/v2/trade</span> routes. Error rate 94%, 1,400 req/min failing. Affects all trade execution and portfolio endpoints. Auth and static routes are unaffected. Rollback attempted — still degraded.
          </div>
        </div>

        <div className="ectx-block">
          <div className="h">What changed last</div>
          <div className="deploy">
            <span className="deploy-v">v2.9.1</span>
            <span className="deploy-t">14:04 UTC · 3m before incident</span>
          </div>
          <div className="deploy-sub">
            Kong plugin config patch · <span className="commit">b7e4c12</span> · author <b>@dtoledo</b>. Updated <span style={{ fontFamily: "var(--font-mono)", fontSize: 12.5, background: "var(--line-soft)", padding: "0 5px", borderRadius: 3 }}>rate_limiting</span> plugin — policy set to <b>local</b> instead of <b>redis</b>, causing all distributed checks to fail open then block.
          </div>
        </div>

        <div className="ectx-block">
          <div className="h">Who to talk to</div>
          <div className="contacts">
            <div className="contact">
              <div className="av c1">AS</div>
              <div className="info">
                <div className="n">Aaron Sokol</div>
                <div className="r">SRE · on-call · live in war room</div>
              </div>
              <div className="handle">@asokol</div>
            </div>
            <div className="contact">
              <div className="av c2">DT</div>
              <div className="info">
                <div className="n">Diego Toledo</div>
                <div className="r">Author of v4.18.2 · paged</div>
              </div>
              <div className="handle">@dtoledo</div>
            </div>
            <div className="contact">
              <div className="av c3">EL</div>
              <div className="info">
                <div className="n">Elena Larsen</div>
                <div className="r">Toptal delivery lead · escalation</div>
              </div>
              <div className="handle">@elena</div>
            </div>
          </div>
        </div>

        <div className="ectx-block">
          <div className="h">Runbooks & logs</div>
          <div className="runs">
            <div className="run">
              <div className="ico"><Ico4.doc/></div>
              <div className="text">
                <div className="t">Runbook · Kong plugin incident response</div>
                <div className="s">runbooks/kong-plugin-recovery.md · last edited 3d ago</div>
              </div>
              <div className="ext"><Ico4.ext/></div>
            </div>
            <div className="run">
              <div className="ico"><Ico4.log/></div>
              <div className="text">
                <div className="t">Live logs · API Gateway /v2/trade routes</div>
                <div className="s">Datadog · last 30min · prefiltered to 503</div>
              </div>
              <div className="ext"><Ico4.ext/></div>
            </div>
            <div className="run">
              <div className="ico"><Ico4.graph/></div>
              <div className="text">
                <div className="t">Dashboard · error rate + Kong plugin status</div>
                <div className="s">Grafana · halyard-api-gateway · sev-1 view</div>
              </div>
              <div className="ext"><Ico4.ext/></div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="ectx-foot">
        <div className="left">
          SLA · <b>7h 03m</b> to resolve · synced 12s ago
        </div>
        <button className="btn btn-ghost">Mark as read</button>
        <button className="btn btn-alert" onClick={onOpenWarRoom}>Open war room <Ico4.arrow4/></button>
      </div>
    </div>
  );

  if (mobile) {
    return (
      <div className="cad ectx-mobile">
        <div className="shell-statusbar">
          <span>9:14</span>
          <div className="icons">
            <svg width="17" height="11" viewBox="0 0 17 11" fill="currentColor">
              <rect x="0" y="7" width="3" height="4" rx="0.5"/>
              <rect x="4.5" y="5" width="3" height="6" rx="0.5"/>
              <rect x="9" y="2.5" width="3" height="8.5" rx="0.5"/>
              <rect x="13.5" y="0" width="3" height="11" rx="0.5"/>
            </svg>
            <svg width="26" height="11" viewBox="0 0 26 11" fill="none">
              <rect x="0.5" y="0.5" width="22" height="10" rx="2.5" stroke="currentColor" strokeWidth="1"/>
              <rect x="2" y="2" width="18" height="7" rx="1.3" fill="currentColor"/>
              <rect x="23.5" y="3.5" width="2" height="4" rx="1" fill="currentColor"/>
            </svg>
          </div>
        </div>
        {card}
      </div>
    );
  }

  return (
    <div className="cad" style={{ padding: 28, background: "var(--paper)", height: "100%", boxSizing: "border-box" }}>
      {card}
    </div>
  );
}

function FrameEmergencyCtx({ onOpenWarRoom }) { return <EmergencyContextCard onOpenWarRoom={onOpenWarRoom} />; }
function FrameEmergencyCtxMobile({ onOpenWarRoom }) { return <EmergencyContextCard mobile onOpenWarRoom={onOpenWarRoom} />; }

export { FrameEmergencyCtx, FrameEmergencyCtxMobile, EmergencyContextCard };
