import React from 'react'
import { useNavigate } from 'react-router-dom'
import { useDemo } from '../demo-store.jsx'
import { FrameEmergencyCtx } from '../screens/screen4.jsx'
import { PageLayout, StepHeader, DesktopFrame } from './shared.jsx'

const CONTACTS = [
  { initials: 'AS', avBg: 'oklch(82% 0.04 60)', name: 'Aaron Sokol', role: 'SRE · on-call · live in war room', handle: '@asokol' },
  { initials: 'DT', avBg: 'oklch(85% 0.04 120)', name: 'Diego Toledo', role: 'Author of v4.18.2 · paged', handle: '@dtoledo' },
  { initials: 'EL', avBg: 'oklch(85% 0.04 220)', name: 'Elena Larsen', role: 'Toptal delivery lead · escalation', handle: '@elena' },
]

const RUNBOOKS = [
  { icon: 'doc', title: 'Runbook · Kong plugin incident response', sub: 'runbooks/kong-plugin-recovery.md · last edited 3d ago' },
  { icon: 'log', title: 'Live logs · API Gateway /v2/trade routes', sub: 'Datadog · last 30min · prefiltered to 503' },
  { icon: 'graph', title: 'Dashboard · error rate + Kong plugin status', sub: 'Grafana · halyard-api-gateway · sev-1 view' },
]

function DocIco() { return <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round" strokeLinecap="round"><path d="M3 1.5 H8 L10.5 4 V11.5 H3 Z"/><path d="M8 1.5 V4 H10.5"/><path d="M5 7 H8.5 M5 9 H8.5"/></svg> }
function LogIco() { return <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"><rect x="2" y="2.5" width="9" height="8" rx="1.2"/><path d="M4 5.5 H9 M4 7.5 H9 M4 9.5 H7"/></svg> }
function GraphIco() { return <svg width="13" height="13" viewBox="0 0 13 13" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M1.5 11 H11.5 M2.5 11 V8 M5 11 V4 M7.5 11 V6 M10 11 V2.5"/></svg> }
function ExtIco() { return <svg width="11" height="11" viewBox="0 0 11 11" fill="none" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round" strokeLinejoin="round"><path d="M5 2 H9 V6 M9 2 L4.5 6.5 M2.5 4 V9 H7.5"/></svg> }

function MobileContextCard({ onOpenWarRoom }) {
  return (
    <div style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: 10 }}>
      {/* P1 header band — full width */}
      <div style={{ background: 'var(--alert)', borderRadius: 8, padding: '12px 16px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: '0.07em', padding: '2px 8px', borderRadius: 999, background: 'rgba(255,255,255,0.2)', color: '#fff' }}>P1 · Production outage</span>
          <span style={{ fontSize: 11, color: 'rgba(255,255,255,0.7)', fontFamily: 'var(--font-mono)' }}>ODT-P1-0042</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
          <span style={{ width: 6, height: 6, borderRadius: '50%', background: '#fff', display: 'inline-block', flexShrink: 0 }} />
          <span style={{ fontSize: 11.5, color: 'rgba(255,255,255,0.85)', fontFamily: 'var(--font-mono)' }}>Context valid · 3h 47m</span>
        </div>
      </div>

      {/* AI-generated headline — full width */}
      <div style={{ background: '#fff', border: '1px solid var(--line)', borderRadius: 8, padding: '14px 16px' }}>
        <div style={{ fontSize: 10.5, color: 'var(--muted)', marginBottom: 8, fontFamily: 'var(--font-mono)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>Generated by Toptal AI · 14:10 UTC · for Priya Nair</div>
        <div style={{ fontSize: 20, fontWeight: 700, color: 'var(--navy)', lineHeight: 1.3, marginBottom: 8 }}>
          API Gateway returning <span style={{ color: 'var(--alert)' }}>503s</span> on all /v2/trade routes — 94% error rate.
        </div>
        <div style={{ fontSize: 12.5, color: 'var(--ink-2)', lineHeight: 1.5 }}>
          <strong>Halyard Capital</strong> · trading platform · degraded since <span style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5 }}>14:07 UTC</span> · 1,400 req/min failing
        </div>
      </div>

      {/* START HERE — full width */}
      <div style={{ background: 'var(--alert-soft)', border: '1px solid #F4C6D2', borderRadius: 8, padding: '12px 14px' }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--alert)', marginBottom: 6 }}>Start here</div>
        <div style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.55 }}>
          Join <strong>#incident-halyard</strong> (war room), then review the Kong rate-limit plugin config in commit <code style={{ background: 'rgba(212,37,81,0.08)', padding: '0 5px', borderRadius: 3, fontFamily: 'var(--font-mono)', fontSize: 11.5 }}>b7e4c12</code>. Aaron Sokol (SRE): rate_limiting config misconfigured in v2.9.1.
        </div>
      </div>

      {/* What is broken */}
      <div style={{ background: '#fff', border: '1px solid var(--line)', borderRadius: 8, padding: '12px 14px' }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 8 }}>What is broken</div>
        <div style={{ fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.55 }}>
          API Gateway returning <strong>503s</strong> on all <code style={{ background: 'var(--line-soft)', padding: '0 4px', borderRadius: 3, fontFamily: 'var(--font-mono)', fontSize: 11.5 }}>/v2/trade</code> routes. Error rate 94%, 1,400 req/min failing. Affects all trade execution and portfolio endpoints. Auth and static routes are unaffected. Rollback attempted — still degraded.
        </div>
      </div>

      {/* What changed last */}
      <div style={{ background: '#fff', border: '1px solid var(--line)', borderRadius: 8, padding: '12px 14px' }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 8 }}>What changed last</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
          <span style={{ fontSize: 12.5, fontWeight: 700, color: 'var(--navy)', fontFamily: 'var(--font-mono)' }}>v2.9.1</span>
          <span style={{ fontSize: 11, color: 'var(--muted)', fontFamily: 'var(--font-mono)' }}>14:04 UTC · 3m before incident</span>
        </div>
        <div style={{ fontSize: 13, color: 'var(--ink-2)', lineHeight: 1.55 }}>
          Kong plugin config patch · <code style={{ fontFamily: 'var(--font-mono)', fontSize: 11.5 }}>b7e4c12</code> · author <strong>@dtoledo</strong>. Updated <code style={{ background: 'var(--line-soft)', padding: '0 4px', borderRadius: 3, fontFamily: 'var(--font-mono)', fontSize: 11.5 }}>rate_limiting</code> plugin — policy set to <strong>local</strong> instead of <strong>redis</strong>, causing all distributed checks to fail open then block.
        </div>
      </div>

      {/* Who to talk to */}
      <div style={{ background: '#fff', border: '1px solid var(--line)', borderRadius: 8, padding: '12px 14px' }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 8 }}>Who to talk to</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {CONTACTS.map((c, i) => (
            <div key={c.handle} style={{ display: 'flex', alignItems: 'center', gap: 10, paddingTop: i > 0 ? 8 : 0, marginTop: i > 0 ? 8 : 0, borderTop: i > 0 ? '1px solid var(--line-soft)' : 'none' }}>
              <div style={{ width: 30, height: 30, borderRadius: '50%', background: c.avBg, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 10.5, fontWeight: 700, color: 'var(--ink)', flexShrink: 0 }}>{c.initials}</div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--navy)' }}>{c.name}</div>
                <div style={{ fontSize: 11, color: 'var(--muted)', marginTop: 1 }}>{c.role}</div>
              </div>
              <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10.5, color: 'var(--clay-ink)', background: 'var(--clay-soft)', padding: '2px 7px', borderRadius: 4, flexShrink: 0, maxWidth: 90, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{c.handle}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Runbooks & logs */}
      <div style={{ background: '#fff', border: '1px solid var(--line)', borderRadius: 8, padding: '12px 14px' }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--muted)', marginBottom: 8 }}>Runbooks &amp; logs</div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
          {RUNBOOKS.map((r, i) => (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 10, paddingTop: i > 0 ? 10 : 0, marginTop: i > 0 ? 10 : 0, borderTop: i > 0 ? '1px solid var(--line-soft)' : 'none' }}>
              <div style={{ width: 28, height: 28, borderRadius: 4, background: 'var(--line-soft)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--muted)', flexShrink: 0 }}>
                {r.icon === 'doc' ? <DocIco /> : r.icon === 'log' ? <LogIco /> : <GraphIco />}
              </div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 12.5, fontWeight: 500, color: 'var(--ink)', marginBottom: 2, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</div>
                <div style={{ fontSize: 11, color: 'var(--muted)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.sub}</div>
              </div>
              <div style={{ color: 'var(--muted)', flexShrink: 0 }}><ExtIco /></div>
            </div>
          ))}
        </div>
      </div>

      {/* SLA info */}
      <div style={{ padding: '4px 2px' }}>
        <span style={{ fontFamily: 'var(--font-mono)', fontSize: 10.5, color: 'var(--muted)', letterSpacing: '0.04em', textTransform: 'uppercase' }}>SLA · <strong style={{ color: 'var(--ink)' }}>7h 03m</strong> to resolve · synced 12s ago</span>
      </div>

      {/* Footer actions — both full width, stacked */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8, paddingBottom: 8 }}>
        <button style={{ width: '100%', minHeight: 44, background: '#fff', border: '1px solid var(--line)', borderRadius: 6, cursor: 'pointer', fontSize: 13, color: 'var(--muted)', fontFamily: 'var(--font-sans)', fontWeight: 500 }}>
          Mark as read
        </button>
        <button
          onClick={onOpenWarRoom}
          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8, width: '100%', minHeight: 44, background: 'var(--alert)', border: 'none', borderRadius: 6, cursor: 'pointer', fontSize: 13, fontWeight: 600, color: '#fff', fontFamily: 'var(--font-sans)' }}
        >
          Open war room
          <svg width="14" height="14" viewBox="0 0 14 14" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M3 7H11M7.5 3.5L11 7L7.5 10.5"/></svg>
        </button>
      </div>
    </div>
  )
}

export default function EmergencyContextCard() {
  const navigate = useNavigate()
  const { reset, set } = useDemo()

  return (
    <PageLayout>
      <StepHeader
        step="Emergency Flow · Step 3 of 4"
        title="Emergency Context Card"
        description="Condensed to outage-relevant information only. Scannable in under 2 minutes. Context valid for 4 hours — generated the moment the SME accepts."
      />

      {/* Desktop — unchanged */}
      <div className="desktop-only">
        <DesktopFrame width={860} minHeight={900}>
          <FrameEmergencyCtx onOpenWarRoom={() => navigate('/emergency/war-room')} />
        </DesktopFrame>
      </div>

      {/* Mobile — new */}
      <div className="mobile-only">
        <MobileContextCard onOpenWarRoom={() => navigate('/emergency/war-room')} />
      </div>

      <div style={{ display: 'flex', gap: 12, flexWrap: 'wrap' }}>
        <button
          onClick={() => { reset(); set({ mode: 'sprint', stage: 'flag' }); navigate('/sprint/gap-flag') }}
          style={{
            background: 'var(--teal)', border: 'none',
            borderRadius: 4, padding: '10px 20px',
            cursor: 'pointer', fontSize: 13.5, fontWeight: 600, color: '#fff',
            display: 'flex', alignItems: 'center', gap: 8,
            transition: 'background 0.15s',
          }}
          onMouseEnter={e => e.currentTarget.style.background = 'var(--blue)'}
          onMouseLeave={e => e.currentTarget.style.background = 'var(--teal)'}
        >
          View sprint flow →
        </button>
        <button
          onClick={() => { reset(); navigate('/') }}
          style={{
            background: 'none', border: '1px solid var(--line)',
            borderRadius: 4, padding: '10px 20px',
            cursor: 'pointer', fontSize: 13, color: 'var(--muted)',
          }}
        >
          ↩ Back to start
        </button>
      </div>
    </PageLayout>
  )
}
